# Generated by Django 3.1.7 on 2021-04-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=40)),
                ('posted_by', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=500)),
                ('location', models.TextField(max_length=255)),
                ('date', models.DateField(verbose_name='Event date (mm/dd/yyyy)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
